name: lcc env
description: Simple action to build and tests e2k code. This action install lcc crosscompiler and qemu-e2k emulator.
author: mrognor
inputs:
  lcc_link:
    required: false
    description: Base crosscompiler link
    default: https://dev.mcst.ru/downloads/2025-03-30/cross-sp-rel-1.27.21.e2k-v5.5.10_64.tgz
  lcc_tarname:
    required: false
    description: Crosscompiler tar archive name
    default: cross-sp-rel-1.27.21.e2k-v5.5.10_64.tgz
  lcc_dirname:
    required: false
    description: Archive dirname
    default: lcc-1.27.21.e2k-v5.5.10
    
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    # Install all requirements
    - name: Install packages
      shell: bash
      run: |
        sudo apt-get update -y 
        sudo apt-get upgrade -y 
        sudo apt-get install -y build-essential ninja-build git python3 python3-pip pkg-config libglib2.0-dev && pip install tomli

    # Install lcc crosscompiler
    - name: Download lcc
      shell: bash
      run: wget ${{ inputs.lcc_link }}

    - name: Unzip lcc
      shell: bash
      run: tar -xzvf ${{ inputs.lcc_tarname }}

    - name: Install lcc
      shell: bash
      run: mv ./opt/mcst /opt

    - name: Clear after lcc install
      shell: bash
      run: rm -r ${{ inputs.lcc_tarname }} opt

    - name: Add lcc bin dir to PATH
      shell: bash
      run: |
        ln -sf /opt/mcst/${{ inputs.lcc_dirname }}/bin/lcc /usr/local/bin/lcc
        ln -sf /opt/mcst/${{ inputs.lcc_dirname }}/bin/l++ /usr/local/bin/l++

    # Install qemu-e2k
    - name: Clone qemu-e2k
      shell: bash
      run: git clone https://github.com/OpenE2K/qemu-e2k.git && cd qemu-e2k && git checkout e2k

    - name: Configure qemu-e2k
      shell: bash
      run: cd qemu-e2k && mkdir build && cd build && ../configure --target-list=e2k-linux-user --static --disable-capstone --disable-werror

    - name: Build qemu-e2k
      shell: bash
      run: cd qemu-e2k/build && nice ninja 
      
    - name: Install qemu-e2k
      shell: bash
      run: |
        cp qemu-e2k/build/qemu-e2k /usr/local/bin
        echo "#!/bin/bash" > /usr/local/bin/e2k
        echo "qemu-e2k -L /opt/mcst/${{ inputs.lcc_dirname }}/fs \$1" >> /usr/local/bin/e2k
        chmod +x /usr/local/bin/e2k

    - name: Clear qemu-e2k
      shell: bash
      run: rm -r qemu-e2k